# Android
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=false

# Kotlin
kotlin.code.style=official

# Gradle
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.daemon=false

# AAPT2
android.enableAapt2=true
